/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSharedRouteImport } from './routes/_authenticated/shared'
import { Route as AuthenticatedMyPollsRouteImport } from './routes/_authenticated/my-polls'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPollsNewRouteImport } from './routes/_authenticated/polls.new'
import { Route as AuthenticatedPollsIdRouteImport } from './routes/_authenticated/polls.$id'
import { Route as AuthenticatedPollsIdEditRouteImport } from './routes/_authenticated/polls.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSharedRoute = AuthenticatedSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyPollsRoute = AuthenticatedMyPollsRouteImport.update({
  id: '/my-polls',
  path: '/my-polls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPollsNewRoute = AuthenticatedPollsNewRouteImport.update({
  id: '/polls/new',
  path: '/polls/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPollsIdRoute = AuthenticatedPollsIdRouteImport.update({
  id: '/polls/$id',
  path: '/polls/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPollsIdEditRoute =
  AuthenticatedPollsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedPollsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/my-polls': typeof AuthenticatedMyPollsRoute
  '/shared': typeof AuthenticatedSharedRoute
  '/polls/$id': typeof AuthenticatedPollsIdRouteWithChildren
  '/polls/new': typeof AuthenticatedPollsNewRoute
  '/polls/$id/edit': typeof AuthenticatedPollsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/my-polls': typeof AuthenticatedMyPollsRoute
  '/shared': typeof AuthenticatedSharedRoute
  '/polls/$id': typeof AuthenticatedPollsIdRouteWithChildren
  '/polls/new': typeof AuthenticatedPollsNewRoute
  '/polls/$id/edit': typeof AuthenticatedPollsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/my-polls': typeof AuthenticatedMyPollsRoute
  '/_authenticated/shared': typeof AuthenticatedSharedRoute
  '/_authenticated/polls/$id': typeof AuthenticatedPollsIdRouteWithChildren
  '/_authenticated/polls/new': typeof AuthenticatedPollsNewRoute
  '/_authenticated/polls/$id/edit': typeof AuthenticatedPollsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/feed'
    | '/my-polls'
    | '/shared'
    | '/polls/$id'
    | '/polls/new'
    | '/polls/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/feed'
    | '/my-polls'
    | '/shared'
    | '/polls/$id'
    | '/polls/new'
    | '/polls/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/feed'
    | '/_authenticated/my-polls'
    | '/_authenticated/shared'
    | '/_authenticated/polls/$id'
    | '/_authenticated/polls/new'
    | '/_authenticated/polls/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shared': {
      id: '/_authenticated/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof AuthenticatedSharedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-polls': {
      id: '/_authenticated/my-polls'
      path: '/my-polls'
      fullPath: '/my-polls'
      preLoaderRoute: typeof AuthenticatedMyPollsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/polls/new': {
      id: '/_authenticated/polls/new'
      path: '/polls/new'
      fullPath: '/polls/new'
      preLoaderRoute: typeof AuthenticatedPollsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/polls/$id': {
      id: '/_authenticated/polls/$id'
      path: '/polls/$id'
      fullPath: '/polls/$id'
      preLoaderRoute: typeof AuthenticatedPollsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/polls/$id/edit': {
      id: '/_authenticated/polls/$id/edit'
      path: '/edit'
      fullPath: '/polls/$id/edit'
      preLoaderRoute: typeof AuthenticatedPollsIdEditRouteImport
      parentRoute: typeof AuthenticatedPollsIdRoute
    }
  }
}

interface AuthenticatedPollsIdRouteChildren {
  AuthenticatedPollsIdEditRoute: typeof AuthenticatedPollsIdEditRoute
}

const AuthenticatedPollsIdRouteChildren: AuthenticatedPollsIdRouteChildren = {
  AuthenticatedPollsIdEditRoute: AuthenticatedPollsIdEditRoute,
}

const AuthenticatedPollsIdRouteWithChildren =
  AuthenticatedPollsIdRoute._addFileChildren(AuthenticatedPollsIdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedMyPollsRoute: typeof AuthenticatedMyPollsRoute
  AuthenticatedSharedRoute: typeof AuthenticatedSharedRoute
  AuthenticatedPollsIdRoute: typeof AuthenticatedPollsIdRouteWithChildren
  AuthenticatedPollsNewRoute: typeof AuthenticatedPollsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedMyPollsRoute: AuthenticatedMyPollsRoute,
  AuthenticatedSharedRoute: AuthenticatedSharedRoute,
  AuthenticatedPollsIdRoute: AuthenticatedPollsIdRouteWithChildren,
  AuthenticatedPollsNewRoute: AuthenticatedPollsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
